spring:
  application:
    name: XmlTagReaderSpringBoot
iso:
  extract:
    commonFields:
      TxId: TxId
      EndToEndId: EndToEndId
      OrgnlTxId: OrgnlTxId
      OrgnlEndToEndId: OrgnlEndToEndId
      AccptncDtTm: AccptncDtTm
      IntrBkSttlmAmt: amount
    pathFields:
      IBAN:
        - path: "DbtrAcct>Id>IBAN"
          key: debtorIBAN
        - path: "CdtrAcct>Id>IBAN"
          key: creditorIBAN
      BICFI:
        - path: "DbtrAgt>FinInstnId>BICFI"
          key: debtorAgentBIC
        - path: "CdtrAgt>FinInstnId>BICFI"
          key: creditorAgentBIC
        - path: "InstgAgt>FinInstnId>BICFI"
          key: initiatingAgentBIC
    defaultValues:
      AccptncDtTm: "2025-01-01T10:00:00Z"
      amount: 0.0